#!/bin/bash

CMD=$0
[ "${CMD:0:1}" != "/" ] && CMD="$PWD/$CMD"
APP=$(dirname "$CMD")
APP="$APP/sdcard/DroidScript/droidscript-web/server/dserve.js"

main() {
        cd "$HOME" # Share node_modules with other node apps

	# Below, choose correct binary modules for our architecture
        v=$(uname -m)
        if [ "$v" = "armv6l" ]; then
                dir="node_modules/fibers/bin/linux-arm-48"
                if [ ! -d "$dir" -a -f linux-arm-48_fibers.node ]; then
                        mkdir -p "$dir" 
                        ln linux-arm-48_fibers.node "$dir/fibers.node"
                fi
                /home/pi/node-armv6l "$APP"
        elif [ "$v" = "armv7l" ]; then
                dir="node_modules/fibers/bin/linux-arm-51"
                if [ ! -d "$dir" -a -f linux-arm-51_fibers.node ]; then
                        mkdir -p "$dir"
                        ln linux-arm-51_fibers.node "$dir/fibers.node"
                fi
                node "$APP"
        else
                node "$APP"
        fi
}

clear
echo "Starting $APP..."
main
